runtime: nodejs14
automatic_scaling:
  target_cpu_utilization: 0.65
handlers:
  - url: /assets/(.*\.(js|css))
    static_files: dist/assets/\1
    upload: dist/assets/.*\.(js|css)
  - url: /(.*\.(js|css))
    static_files: dist/\1
    upload: dist/.*\.(js|css)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
# https://norse-bond-299713.lm.r.appspot.com/
